// Generated by gencpp from file alexa_ros/AlexaTaskGoal.msg
// DO NOT EDIT!


#ifndef ALEXA_ROS_MESSAGE_ALEXATASKGOAL_H
#define ALEXA_ROS_MESSAGE_ALEXATASKGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace alexa_ros
{
template <class ContainerAllocator>
struct AlexaTaskGoal_
{
  typedef AlexaTaskGoal_<ContainerAllocator> Type;

  AlexaTaskGoal_()
    : task_number(0)  {
    }
  AlexaTaskGoal_(const ContainerAllocator& _alloc)
    : task_number(0)  {
  (void)_alloc;
    }



   typedef int64_t _task_number_type;
  _task_number_type task_number;





  typedef boost::shared_ptr< ::alexa_ros::AlexaTaskGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::alexa_ros::AlexaTaskGoal_<ContainerAllocator> const> ConstPtr;

}; // struct AlexaTaskGoal_

typedef ::alexa_ros::AlexaTaskGoal_<std::allocator<void> > AlexaTaskGoal;

typedef boost::shared_ptr< ::alexa_ros::AlexaTaskGoal > AlexaTaskGoalPtr;
typedef boost::shared_ptr< ::alexa_ros::AlexaTaskGoal const> AlexaTaskGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::alexa_ros::AlexaTaskGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::alexa_ros::AlexaTaskGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::alexa_ros::AlexaTaskGoal_<ContainerAllocator1> & lhs, const ::alexa_ros::AlexaTaskGoal_<ContainerAllocator2> & rhs)
{
  return lhs.task_number == rhs.task_number;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::alexa_ros::AlexaTaskGoal_<ContainerAllocator1> & lhs, const ::alexa_ros::AlexaTaskGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace alexa_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::alexa_ros::AlexaTaskGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::alexa_ros::AlexaTaskGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::alexa_ros::AlexaTaskGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::alexa_ros::AlexaTaskGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::alexa_ros::AlexaTaskGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::alexa_ros::AlexaTaskGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::alexa_ros::AlexaTaskGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a44f0e3523e87134465bfb1a1ffe53cc";
  }

  static const char* value(const ::alexa_ros::AlexaTaskGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa44f0e3523e87134ULL;
  static const uint64_t static_value2 = 0x465bfb1a1ffe53ccULL;
};

template<class ContainerAllocator>
struct DataType< ::alexa_ros::AlexaTaskGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "alexa_ros/AlexaTaskGoal";
  }

  static const char* value(const ::alexa_ros::AlexaTaskGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::alexa_ros::AlexaTaskGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Goal         \n"
"int64 task_number\n"
;
  }

  static const char* value(const ::alexa_ros::AlexaTaskGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::alexa_ros::AlexaTaskGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.task_number);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AlexaTaskGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::alexa_ros::AlexaTaskGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::alexa_ros::AlexaTaskGoal_<ContainerAllocator>& v)
  {
    s << indent << "task_number: ";
    Printer<int64_t>::stream(s, indent + "  ", v.task_number);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ALEXA_ROS_MESSAGE_ALEXATASKGOAL_H
