// Generated by gencpp from file alexa_ros/AlexaTaskResult.msg
// DO NOT EDIT!


#ifndef ALEXA_ROS_MESSAGE_ALEXATASKRESULT_H
#define ALEXA_ROS_MESSAGE_ALEXATASKRESULT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace alexa_ros
{
template <class ContainerAllocator>
struct AlexaTaskResult_
{
  typedef AlexaTaskResult_<ContainerAllocator> Type;

  AlexaTaskResult_()
    : success(false)  {
    }
  AlexaTaskResult_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::alexa_ros::AlexaTaskResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::alexa_ros::AlexaTaskResult_<ContainerAllocator> const> ConstPtr;

}; // struct AlexaTaskResult_

typedef ::alexa_ros::AlexaTaskResult_<std::allocator<void> > AlexaTaskResult;

typedef boost::shared_ptr< ::alexa_ros::AlexaTaskResult > AlexaTaskResultPtr;
typedef boost::shared_ptr< ::alexa_ros::AlexaTaskResult const> AlexaTaskResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::alexa_ros::AlexaTaskResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::alexa_ros::AlexaTaskResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::alexa_ros::AlexaTaskResult_<ContainerAllocator1> & lhs, const ::alexa_ros::AlexaTaskResult_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::alexa_ros::AlexaTaskResult_<ContainerAllocator1> & lhs, const ::alexa_ros::AlexaTaskResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace alexa_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::alexa_ros::AlexaTaskResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::alexa_ros::AlexaTaskResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::alexa_ros::AlexaTaskResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::alexa_ros::AlexaTaskResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::alexa_ros::AlexaTaskResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::alexa_ros::AlexaTaskResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::alexa_ros::AlexaTaskResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::alexa_ros::AlexaTaskResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::alexa_ros::AlexaTaskResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "alexa_ros/AlexaTaskResult";
  }

  static const char* value(const ::alexa_ros::AlexaTaskResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::alexa_ros::AlexaTaskResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Result\n"
"bool success\n"
;
  }

  static const char* value(const ::alexa_ros::AlexaTaskResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::alexa_ros::AlexaTaskResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AlexaTaskResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::alexa_ros::AlexaTaskResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::alexa_ros::AlexaTaskResult_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ALEXA_ROS_MESSAGE_ALEXATASKRESULT_H
