// Generated by gencpp from file alexa_ros/AlexaTaskActionGoal.msg
// DO NOT EDIT!


#ifndef ALEXA_ROS_MESSAGE_ALEXATASKACTIONGOAL_H
#define ALEXA_ROS_MESSAGE_ALEXATASKACTIONGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <actionlib_msgs/GoalID.h>
#include <alexa_ros/AlexaTaskGoal.h>

namespace alexa_ros
{
template <class ContainerAllocator>
struct AlexaTaskActionGoal_
{
  typedef AlexaTaskActionGoal_<ContainerAllocator> Type;

  AlexaTaskActionGoal_()
    : header()
    , goal_id()
    , goal()  {
    }
  AlexaTaskActionGoal_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , goal_id(_alloc)
    , goal(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::actionlib_msgs::GoalID_<ContainerAllocator>  _goal_id_type;
  _goal_id_type goal_id;

   typedef  ::alexa_ros::AlexaTaskGoal_<ContainerAllocator>  _goal_type;
  _goal_type goal;





  typedef boost::shared_ptr< ::alexa_ros::AlexaTaskActionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::alexa_ros::AlexaTaskActionGoal_<ContainerAllocator> const> ConstPtr;

}; // struct AlexaTaskActionGoal_

typedef ::alexa_ros::AlexaTaskActionGoal_<std::allocator<void> > AlexaTaskActionGoal;

typedef boost::shared_ptr< ::alexa_ros::AlexaTaskActionGoal > AlexaTaskActionGoalPtr;
typedef boost::shared_ptr< ::alexa_ros::AlexaTaskActionGoal const> AlexaTaskActionGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::alexa_ros::AlexaTaskActionGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::alexa_ros::AlexaTaskActionGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::alexa_ros::AlexaTaskActionGoal_<ContainerAllocator1> & lhs, const ::alexa_ros::AlexaTaskActionGoal_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.goal_id == rhs.goal_id &&
    lhs.goal == rhs.goal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::alexa_ros::AlexaTaskActionGoal_<ContainerAllocator1> & lhs, const ::alexa_ros::AlexaTaskActionGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace alexa_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::alexa_ros::AlexaTaskActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::alexa_ros::AlexaTaskActionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::alexa_ros::AlexaTaskActionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::alexa_ros::AlexaTaskActionGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::alexa_ros::AlexaTaskActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::alexa_ros::AlexaTaskActionGoal_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::alexa_ros::AlexaTaskActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "25dbc7123bf39d0ae8bdb43ed5637e31";
  }

  static const char* value(const ::alexa_ros::AlexaTaskActionGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x25dbc7123bf39d0aULL;
  static const uint64_t static_value2 = 0xe8bdb43ed5637e31ULL;
};

template<class ContainerAllocator>
struct DataType< ::alexa_ros::AlexaTaskActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "alexa_ros/AlexaTaskActionGoal";
  }

  static const char* value(const ::alexa_ros::AlexaTaskActionGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::alexa_ros::AlexaTaskActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalID goal_id\n"
"AlexaTaskGoal goal\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalID\n"
"# The stamp should store the time at which this goal was requested.\n"
"# It is used by an action server when it tries to preempt all\n"
"# goals that were requested before a certain time\n"
"time stamp\n"
"\n"
"# The id provides a way to associate feedback and\n"
"# result message with specific goal requests. The id\n"
"# specified must be unique.\n"
"string id\n"
"\n"
"\n"
"================================================================================\n"
"MSG: alexa_ros/AlexaTaskGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Goal         \n"
"int64 task_number\n"
;
  }

  static const char* value(const ::alexa_ros::AlexaTaskActionGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::alexa_ros::AlexaTaskActionGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.goal_id);
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AlexaTaskActionGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::alexa_ros::AlexaTaskActionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::alexa_ros::AlexaTaskActionGoal_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "goal_id: ";
    s << std::endl;
    Printer< ::actionlib_msgs::GoalID_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_id);
    s << indent << "goal: ";
    s << std::endl;
    Printer< ::alexa_ros::AlexaTaskGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ALEXA_ROS_MESSAGE_ALEXATASKACTIONGOAL_H
