// Generated by gencpp from file alexa_ros/AlexaTaskFeedback.msg
// DO NOT EDIT!


#ifndef ALEXA_ROS_MESSAGE_ALEXATASKFEEDBACK_H
#define ALEXA_ROS_MESSAGE_ALEXATASKFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace alexa_ros
{
template <class ContainerAllocator>
struct AlexaTaskFeedback_
{
  typedef AlexaTaskFeedback_<ContainerAllocator> Type;

  AlexaTaskFeedback_()
    : percentage(0.0)  {
    }
  AlexaTaskFeedback_(const ContainerAllocator& _alloc)
    : percentage(0.0)  {
  (void)_alloc;
    }



   typedef double _percentage_type;
  _percentage_type percentage;





  typedef boost::shared_ptr< ::alexa_ros::AlexaTaskFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::alexa_ros::AlexaTaskFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct AlexaTaskFeedback_

typedef ::alexa_ros::AlexaTaskFeedback_<std::allocator<void> > AlexaTaskFeedback;

typedef boost::shared_ptr< ::alexa_ros::AlexaTaskFeedback > AlexaTaskFeedbackPtr;
typedef boost::shared_ptr< ::alexa_ros::AlexaTaskFeedback const> AlexaTaskFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::alexa_ros::AlexaTaskFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::alexa_ros::AlexaTaskFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::alexa_ros::AlexaTaskFeedback_<ContainerAllocator1> & lhs, const ::alexa_ros::AlexaTaskFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.percentage == rhs.percentage;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::alexa_ros::AlexaTaskFeedback_<ContainerAllocator1> & lhs, const ::alexa_ros::AlexaTaskFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace alexa_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::alexa_ros::AlexaTaskFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::alexa_ros::AlexaTaskFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::alexa_ros::AlexaTaskFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::alexa_ros::AlexaTaskFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::alexa_ros::AlexaTaskFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::alexa_ros::AlexaTaskFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::alexa_ros::AlexaTaskFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "46302a97c06fe5a4416c427fe6ee8804";
  }

  static const char* value(const ::alexa_ros::AlexaTaskFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x46302a97c06fe5a4ULL;
  static const uint64_t static_value2 = 0x416c427fe6ee8804ULL;
};

template<class ContainerAllocator>
struct DataType< ::alexa_ros::AlexaTaskFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "alexa_ros/AlexaTaskFeedback";
  }

  static const char* value(const ::alexa_ros::AlexaTaskFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::alexa_ros::AlexaTaskFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Feedback\n"
"float64 percentage\n"
"\n"
;
  }

  static const char* value(const ::alexa_ros::AlexaTaskFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::alexa_ros::AlexaTaskFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.percentage);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AlexaTaskFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::alexa_ros::AlexaTaskFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::alexa_ros::AlexaTaskFeedback_<ContainerAllocator>& v)
  {
    s << indent << "percentage: ";
    Printer<double>::stream(s, indent + "  ", v.percentage);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ALEXA_ROS_MESSAGE_ALEXATASKFEEDBACK_H
