(cl:defpackage alexa_ros-msg
  (:use )
  (:export
   "<ALEXATASKACTION>"
   "ALEXATASKACTION"
   "<ALEXATASKACTIONFEEDBACK>"
   "ALEXATASKACTIONFEEDBACK"
   "<ALEXATASKACTIONGOAL>"
   "ALEXATASKACTIONGOAL"
   "<ALEXATASKACTIONRESULT>"
   "ALEXATASKACTIONRESULT"
   "<ALEXATASKFEEDBACK>"
   "ALEXATASKFEEDBACK"
   "<ALEXATASKGOAL>"
   "ALEXATASKGOAL"
   "<ALEXATASKRESULT>"
   "ALEXATASKRESULT"
  ))

