; Auto-generated. Do not edit!


(cl:in-package alexa_ros-msg)


;//! \htmlinclude AlexaTaskFeedback.msg.html

(cl:defclass <AlexaTaskFeedback> (roslisp-msg-protocol:ros-message)
  ((percentage
    :reader percentage
    :initarg :percentage
    :type cl:float
    :initform 0.0))
)

(cl:defclass AlexaTaskFeedback (<AlexaTaskFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <AlexaTaskFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'AlexaTaskFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name alexa_ros-msg:<AlexaTaskFeedback> is deprecated: use alexa_ros-msg:AlexaTaskFeedback instead.")))

(cl:ensure-generic-function 'percentage-val :lambda-list '(m))
(cl:defmethod percentage-val ((m <AlexaTaskFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader alexa_ros-msg:percentage-val is deprecated.  Use alexa_ros-msg:percentage instead.")
  (percentage m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <AlexaTaskFeedback>) ostream)
  "Serializes a message object of type '<AlexaTaskFeedback>"
  (cl:let ((bits (roslisp-utils:encode-double-float-bits (cl:slot-value msg 'percentage))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <AlexaTaskFeedback>) istream)
  "Deserializes a message object of type '<AlexaTaskFeedback>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'percentage) (roslisp-utils:decode-double-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<AlexaTaskFeedback>)))
  "Returns string type for a message object of type '<AlexaTaskFeedback>"
  "alexa_ros/AlexaTaskFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'AlexaTaskFeedback)))
  "Returns string type for a message object of type 'AlexaTaskFeedback"
  "alexa_ros/AlexaTaskFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<AlexaTaskFeedback>)))
  "Returns md5sum for a message object of type '<AlexaTaskFeedback>"
  "46302a97c06fe5a4416c427fe6ee8804")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'AlexaTaskFeedback)))
  "Returns md5sum for a message object of type 'AlexaTaskFeedback"
  "46302a97c06fe5a4416c427fe6ee8804")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<AlexaTaskFeedback>)))
  "Returns full string definition for message of type '<AlexaTaskFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Feedback~%float64 percentage~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'AlexaTaskFeedback)))
  "Returns full string definition for message of type 'AlexaTaskFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Feedback~%float64 percentage~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <AlexaTaskFeedback>))
  (cl:+ 0
     8
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <AlexaTaskFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'AlexaTaskFeedback
    (cl:cons ':percentage (percentage msg))
))
