; Auto-generated. Do not edit!


(cl:in-package alexa_ros-msg)


;//! \htmlinclude AlexaTaskResult.msg.html

(cl:defclass <AlexaTaskResult> (roslisp-msg-protocol:ros-message)
  ((success
    :reader success
    :initarg :success
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass AlexaTaskResult (<AlexaTaskResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <AlexaTaskResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'AlexaTaskResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name alexa_ros-msg:<AlexaTaskResult> is deprecated: use alexa_ros-msg:AlexaTaskResult instead.")))

(cl:ensure-generic-function 'success-val :lambda-list '(m))
(cl:defmethod success-val ((m <AlexaTaskResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader alexa_ros-msg:success-val is deprecated.  Use alexa_ros-msg:success instead.")
  (success m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <AlexaTaskResult>) ostream)
  "Serializes a message object of type '<AlexaTaskResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'success) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <AlexaTaskResult>) istream)
  "Deserializes a message object of type '<AlexaTaskResult>"
    (cl:setf (cl:slot-value msg 'success) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<AlexaTaskResult>)))
  "Returns string type for a message object of type '<AlexaTaskResult>"
  "alexa_ros/AlexaTaskResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'AlexaTaskResult)))
  "Returns string type for a message object of type 'AlexaTaskResult"
  "alexa_ros/AlexaTaskResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<AlexaTaskResult>)))
  "Returns md5sum for a message object of type '<AlexaTaskResult>"
  "358e233cde0c8a8bcfea4ce193f8fc15")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'AlexaTaskResult)))
  "Returns md5sum for a message object of type 'AlexaTaskResult"
  "358e233cde0c8a8bcfea4ce193f8fc15")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<AlexaTaskResult>)))
  "Returns full string definition for message of type '<AlexaTaskResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Result~%bool success~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'AlexaTaskResult)))
  "Returns full string definition for message of type 'AlexaTaskResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Result~%bool success~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <AlexaTaskResult>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <AlexaTaskResult>))
  "Converts a ROS message object to a list"
  (cl:list 'AlexaTaskResult
    (cl:cons ':success (success msg))
))
